# Generated by Django 2.2.4 on 2019-09-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190904_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user_id',
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.ManyToManyField(to='portal.UserDetail'),
        ),
    ]
