# Generated by Django 2.2.4 on 2019-09-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190905_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='document',
            name='user_id',
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(default=12121, on_delete=django.db.models.deletion.CASCADE, to='portal.UserDetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
