# Generated by Django 2.2.4 on 2019-09-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190905_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
